# Generated by Django 4.1.5 on 2023-01-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Address_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Address_line_2',
            new_name='address_line_2',
        ),
    ]
