# Generated by Django 4.1.5 on 2023-01-26 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_pincode_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
    ]
